version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_ctn
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php7
      - php8
      - mysql
      - postgres
    networks:
      - web_net

  php7:
    build:
      context: ./docker/php
      args:
        PHP_VERSION: 7.2-fpm
    container_name: php7_ctn
    volumes:
      - ./www:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - web_net

  php8:
    build:
      context: ./docker/php
      args:
        PHP_VERSION: 8.2-fpm
    container_name: php8_ctn
    volumes:
      - ./www:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - web_net

  mysql:
    image: mysql:5.7.33
    container_name: mysql_ctn
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_R}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_v:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    command: --sql_mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    ports:
      - "3306:3306"
    networks:
      - web_net

  postgres:
    image: postgres:latest
    container_name: postgres_ctn
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - postgres_v:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - web_net

volumes:
  mysql_v:
    name: mysql_vol
  postgres_v:
    name: postgres_vol

networks:
  web_net:
    driver: bridge