# docker/nginx/conf.d/php8pro2o.conf

server {
    listen 80;
    server_name php8pro2o.localhost;

    root /var/www/html/php8/php8pro2o/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include /etc/nginx/fastcgi_params;
        fastcgi_pass php8_backend;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}