# docker/nginx/conf.d/sis8.conf

server {
    listen 80;
    server_name sis8.localhost;

    root /var/www/html/php8;
    index index.php index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /php8pro2o/public {
        autoindex off;
        try_files $uri $uri /php8pro2o/public/index.php?$args;
    }

    location ~ \.php$ {
        include /etc/nginx/fastcgi_params;
        fastcgi_pass php8_backend;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}